parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  app.guzzle:
    class: \GuzzleHttp\Client

  App\Services\Requester\Project:
    arguments:
      $client: '@app.guzzle'
